version: "3.8"

services:
  ical-poke-bridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ical-poke-bridge
    ports:
      - "50140:8000"
    environment:
      # Required - iCloud Credentials
      - ICLOUD_EMAIL=${ICLOUD_EMAIL}
      - ICLOUD_PASSWORD=${ICLOUD_PASSWORD}

      # Optional - Server Configuration
      - PORT=8000
      - ENVIRONMENT=${ENVIRONMENT:-production}

    # Restart policy
    restart: unless-stopped

    # Resource limits (adjust as needed)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"

    # Network configuration
    networks:
      - ical-bridge-network

# Optional: separate network for isolation
networks:
  ical-bridge-network:
    driver: bridge

# Optional: volumes for persistent data
volumes:
  logs:
    driver: local
