[project]
name = "ical-poke-bridge"
version = "0.1.0"
description = "iCloud calendar integration for Poke"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "caldav>=1.3.9",
    "fastmcp>=2.12.0",
    "icalendar>=5.0.12",
    "uvicorn>=0.35.0",
]
